### PR TITLE
Subtitles are Back

### PR DESCRIPTION
**Pull request by JokeBambi**
also this is my first pull request and these are the only files i could find for the subtitles and code lines so dont blame me if i did something wrong

### CODE REVIEW

**Comment by JokeBambi** [comment]
> when memehoovy adds an event system, maybe (noice)

hoping just hoping, well hoping events would be in haxe lol but character json would be nice

**Comment by JokeBambi** [comment]
> > > when memehoovy adds an event system, maybe (noice)
> > 
> > 
> > hoping just hoping, well hoping events would be in haxe lol but character json would be also nice
> 
> i tried softcoding characters in this engine tho

oh ig it wont works

**Comment by MemeHovy** [comment]
> when memehoovy adds an event system, maybe

if Erizur allows it then sure

**Comment by MemeHovy** [comment]
there's still more that could be done here, but can be fixed/added after the merge tho

**Comment by MemeHovy** [comment]
thanks!

**Comment by JokeBambi** [comment]
np

**Pull request merged**
