### PR TITLE
botplay 

### PR DESCRIPTION
**Pull request by charlesisfeline**
not sure if erizur allows this but since im tired of spamming (and some engines like Psych and Kade, have Botplay) i decided to make botplay a real option so you dont have to compile just for botplay (it was unused in vs dave so why not)

also this might need testing since its buggy but its sort of on par with kade's botplay so please dont blame me for that

### CODE REVIEW

**Comment by JokeBambi** [comment]
hmm lets review

**Review by JokeBambi — APPROVED** [review]
nice but why do we even need botplay first of all its not like people are gonna make fansongs that are spammy lol

**Comment by JokeBambi** [comment]
actually nvm good point

**Comment by JokeBambi** [comment]
> > nice but why do we even need botplay first of all its not like people are gonna make fansongs that are spammy lol
> 
> botplay doesnt work well with spammy fansongs tho!!!! but its probably for those who are too lazy to spam yet is bad at fnf

hope erizur allows this since im bad at fnf myself so ye

**Comment by MemeHovy** [comment]
well since @CharlesCatYT you decided to abandon the PR, I'll fix the issues myself then

**Comment by MemeHovy** [comment]
> > well since @CharlesCatYT you decided to abandon the PR, I'll fix the issues myself then
> 
> i didnt, i was busy on other shit

alright

**Pull request merged**
